[package]
name = "priority_queue"
version = "0.1.0"
authors = ["net_flasher <net_flasher@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
